[package]
name = "knot-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7"
prometheus = "0.13.1"
thiserror = "1.0"
tide = "0.14.0"
async-std = { version = "1.6.0", features = ["attributes"] }
argh = "0.1.8"

[build-dependencies]
bindgen = "0.60.1"

[profile.release]
opt-level = 1
